services:
  mariadb:
    image: ${MARIADB_IMAGE}
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./mariadb/healthcheck.sh:/healthcheck.sh:ro
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "bash", "/healthcheck.sh"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 120s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m

  wordpress:
    image: ${WORDPRESS_IMAGE}
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - ./.env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
#     WORDPRESS_CONFIG_EXTRA: define('FORCE_SSL_ADMIN', true);define('WP_HOME', 'https://${DOMAIN}');define('WP_SITEURL', 'https://${DOMAIN}');define('WP_DEBUG', true);define('WP_DEBUG_LOG', true);define('WP_DEBUG_DISPLAY', false);
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network
      - proxy-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.services.wordpress.loadbalancer.server.port=${WP_PORT}"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.routers.wordpress.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.wordpress.tls.domains[0].sans=www.${DOMAIN}"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512m

volumes:
  mariadb_data:
  wordpress_data:

networks:
  app-network:
    driver: bridge
  proxy-net:
    external: true
    name: proxy-net