services:
  loki:
    image: ${LOKI_IMAGE}
    volumes:
      - ./loki/loki-config.yaml:/config/config.yaml
    env_file:
      - ./.env
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3100/ready | grep ready"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m

  promtail:
    image: ${PROMTAIL_IMAGE}
    volumes:
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail.yaml
      - /var/log/{$APP_NAME}/traefik:/var/log/:ro
    env_file:
      - ./.env
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pidof promtail || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m

  grafana:
    image: ${GRAFANA_IMAGE}
    env_file:
      - ./.env
    networks:
      - app-network
      - proxy-net
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000 | grep stylesheet"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_DOMAIN}`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.routers.grafana.tls.certresolver=${CERT_RESOLVER}"
      - "traefik.http.routers.grafana.tls.domains[0].main=${DOMAIN}"
      - "traefik.http.routers.grafana.tls.domains[0].sans=www.${DOMAIN},${TRAEFIK_DOMAIN},${GRAFANA_DOMAIN}"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 256m

volumes: {}

networks:
  app-network:
    driver: bridge
  proxy-net:
    external: true
    name: proxy-net