
services:
  matomo:
    image: ${MATOMO_IMAGE}
    env_file:
      - ./.env
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - MATOMO_DATABASE_HOST=mariadb
      - MATOMO_DATABASE_USERNAME=${MATOMO_USER}
      - MATOMO_DATABASE_PASSWORD=${MATOMO_PASSWORD}
      - MATOMO_DATABASE_DBNAME=${MATOMO_DATABASE}
      - MATOMO_ENABLE_AUTH_HTTP=0
    ports:
      - "${MATOMO_HTTP_PORT}:80"
    volumes:
      - matomo_data:/var/www/html
    networks:
      - ${APP_NAME}-app-network

volumes:
  matomo_data:

networks:
  ${APP_NAME}-app-network:
    driver: bridge
